logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.netflix.feign: DEBUG
    okhttp.feign: DEBUG
    org.java10.scs.test1: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:5000/auth/users/current