server:
  port: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /auth/**
        url: http://127.0.0.1:5000
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    test1-service:
       path: /test1/**
       serviceId: test1-service
       stripPrefix: false
       sensitiveHeaders:

    test2-service:
       path: /test2/**
       serviceId: test2-service
       stripPrefix: false
       sensitiveHeaders: